---

- name: Install python2.7 when not present
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Install ansible and python 2.7
      raw: apt-get update && apt-get install --yes ansible

- name: Common tasks
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/group-variables.yaml"
  roles:
    - role_name
  tasks:
    - include: tasks/global_task.yaml


- name: Nginx tasks
  hosts: tag_Role_value #used for dynamic inventory: ec2 with tag Role == value
  become: yes
  become_method: sudo
  vars_files:
    - "group_vars/group-variables.yaml"
  tasks:
    - include: tasks/task.yaml
